services:
  - type: web
    name: canvas-crafters-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 # Render sets this automatically
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://canvas-crafters-iwxr-qtp32huz2-venny-shirus-projects.vercel.app
      - key: EMAIL_FROM
        value: "Canvas Crafters <noreply@canvascrafters.com>"
      - key: EMAIL_PASSWORD
        sync: false
    autoDeploy: true
    rootDir: server
